const express = require("express")
const router = express.Router()
const livereviewHandler = require('./livereviewHandler')
const messvendorsHandler = require('./messvendorsHandler')
const confirmmessHandler = require('./confirmmessHandler')
const { livemenuHandler, uploadimageHandler } = require("./livemenuHandler")
const {authenticateHandler, hashHandler, hashcompHandler} = require("../authenticateHandler")
const {historyHandler,payEatHandler}=require("./paymentHandler")
const feedbackHandler = require("./feedbackHandler")

router.post('/payeat',hashHandler, payEatHandler)
router.post('/feedback',hashHandler, feedbackHandler)
router.post('/uploadimage',hashHandler, uploadimageHandler)
router.get('/livereview/:param1',hashHandler, livereviewHandler)
router.get('/messvendors',hashHandler, messvendorsHandler)
router.get('/confirmmess/:param1', hashHandler, confirmmessHandler)
router.get('/livemenu/:param1',hashHandler, livemenuHandler)
router.get('/historyhandler',hashHandler, historyHandler)

module.exports = router
